
set base_path /app/mirror-syncs/test-config
set mirror_path /app/mirror-syncs/test-config/mirror
set skel_path /app/mirror-syncs/test-config/skel
set var_path /app/mirror-syncs/test-config/var
set cleanscript /app/mirror-syncs/test-config/clean.sh
set defaultarch amd64
set postmirror_script /app/mirror-syncs/test-config/postmirror.sh
set run_postmirror 0
set nthreads 4
set _tilde 0
set timeout 120
set retries 2
set no_check_certificate 1



deb http://archive.kylinos.cn/kylin/KYLIN-ALL/ 10.1 main restricted universe multiverse

